---
- hosts: localhost
  tasks:
    - name: Pull Docker image from Docker Hub
      shell: docker pull someshawasthi/mini-project:latest

    - name: Run Docker container
      shell: /usr/bin/docker run -it -d someshawasthi/mini-project:latest